#!/bin/bash
# Supabase + Cloudflare 配置脚本 (Git Bash / macOS / Linux)
# 用法: bash scripts/setup-supabase-cloudflare.sh

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env.local"

echo ""
echo "========================================"
echo " Conan AI - Supabase + Cloudflare 配置向导"
echo "========================================"
echo ""

read -p "NEXT_PUBLIC_SUPABASE_URL: " SUPABASE_URL
read -p "NEXT_PUBLIC_SUPABASE_ANON_KEY: " ANON_KEY
read -sp "SUPABASE_SERVICE_ROLE_KEY: " SERVICE_KEY
echo ""
read -p "SILICONFLOW_API_KEY (可选，本地开发): " SF_KEY

{
  echo "# Generated by setup-supabase-cloudflare.sh"
  echo "NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL"
  echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY"
  echo "SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY"
  [ -n "$SF_KEY" ] && echo "SILICONFLOW_API_KEY=$SF_KEY"
} > "$ENV_FILE"
echo "  已写入 $ENV_FILE"

echo ""
echo "请在 Supabase SQL Editor 执行: supabase/migrations/000_combined_all.sql"
read -p "迁移完成后按 Enter 继续..."

read -p "Cloudflare Workers URL (例 https://xxx.workers.dev): " SITE_URL
echo "Supabase Auth 回调: $SITE_URL/auth/callback"
echo "                  http://localhost:3000/auth/callback"

echo ""
echo "[5/5] Cloudflare Workers 密钥"
if command -v npx &>/dev/null; then
  npx wrangler whoami >/dev/null 2>&1 || npx wrangler login
  printf '%s' "$SUPABASE_URL" | npx wrangler secret put NEXT_PUBLIC_SUPABASE_URL
  printf '%s' "$ANON_KEY" | npx wrangler secret put NEXT_PUBLIC_SUPABASE_ANON_KEY
  printf '%s' "$SERVICE_KEY" | npx wrangler secret put SUPABASE_SERVICE_ROLE_KEY
  [ -n "$SF_KEY" ] && printf '%s' "$SF_KEY" | npx wrangler secret put SILICONFLOW_API_KEY
  echo "  已同步到 Cloudflare"
  read -p "是否立即部署? (y/n): " REDEPLOY
  [ "$REDEPLOY" = "y" ] && npm run deploy
else
  echo "  未找到 npx，请手动在 Cloudflare Dashboard 添加环境变量"
fi

echo ""
echo "配置完成! 本地: npm run dev"
