#!/bin/bash
# Supabase + Netlify 配置脚本 (Git Bash / macOS / Linux)
# 用法: bash scripts/setup-supabase-netlify.sh

set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env.local"

echo ""
echo "========================================"
echo " Conan AI - Supabase + Netlify 配置向导"
echo "========================================"
echo ""

echo "[1/5] Supabase 项目"
echo "  若尚未创建: https://supabase.com/dashboard/new"
echo ""

read -p "NEXT_PUBLIC_SUPABASE_URL: " SUPABASE_URL
read -p "NEXT_PUBLIC_SUPABASE_ANON_KEY: " ANON_KEY
read -sp "SUPABASE_SERVICE_ROLE_KEY: " SERVICE_KEY
echo ""

if [ -z "$SUPABASE_URL" ] || [ -z "$ANON_KEY" ] || [ -z "$SERVICE_KEY" ]; then
  echo "错误: Supabase 三个变量均为必填"
  exit 1
fi

echo ""
echo "[2/5] 写入 .env.local"

# 保留已有 SILICONFLOW_API_KEY
SF_KEY=""
if [ -f "$ENV_FILE" ]; then
  SF_KEY=$(grep -E '^SILICONFLOW_API_KEY=' "$ENV_FILE" | cut -d= -f2- || true)
fi
if [ -z "$SF_KEY" ]; then
  read -p "SILICONFLOW_API_KEY: " SF_KEY
fi

cat > "$ENV_FILE" << EOF
# Generated by setup-supabase-netlify.sh
# $(date)

SILICONFLOW_API_KEY=$SF_KEY
NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY
EOF

echo "  已更新 $ENV_FILE"

echo ""
echo "[3/5] 数据库迁移"
echo "  在 Supabase SQL Editor 执行:"
echo "  $ROOT/supabase/migrations/000_combined_all.sql"
read -p "迁移完成后按 Enter 继续..."

echo ""
echo "[4/5] Auth 回调 URL"
read -p "Netlify 站点 URL (例 https://xxx.netlify.app): " SITE_URL
echo "  在 Supabase Auth URL Configuration 添加:"
echo "  Site URL: $SITE_URL"
echo "  Redirect: http://localhost:3000/auth/callback"
echo "  Redirect: $SITE_URL/auth/callback"
read -p "Auth 配置完成后按 Enter 继续..."

echo ""
echo "[5/5] Netlify 环境变量"
if command -v netlify &>/dev/null; then
  netlify env:set NEXT_PUBLIC_SUPABASE_URL "$SUPABASE_URL"
  netlify env:set NEXT_PUBLIC_SUPABASE_ANON_KEY "$ANON_KEY"
  netlify env:set SUPABASE_SERVICE_ROLE_KEY "$SERVICE_KEY"
  [ -n "$SF_KEY" ] && netlify env:set SILICONFLOW_API_KEY "$SF_KEY"
  echo "  已同步到 Netlify"
  read -p "立即生产部署? (y/n): " REDEPLOY
  [ "$REDEPLOY" = "y" ] && netlify deploy --prod
else
  echo "  未安装 netlify CLI，请手动在 Dashboard 添加环境变量"
fi

echo ""
echo "配置完成! 运行 npm run dev 本地验证"
